### ISSUE TITLE
Update example to use reverse port forwarding

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-Python-Android-AltTrashCat#1]
## Description
 
- Change in the setup the port forwarding with reverse port forwarding
- Update the AltTester-Driver version
- Update the README.md file
## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1139
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
The testing results can be seen in: https://github.com/alttester/EXAMPLES-Python-Android-AltTrashCat/pull/5

I will move this ticket into `Done`.
